apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:  # ✅ RIGHT PLACE
    argocd-image-updater.argoproj.io.image-list: docker.io/sivakrishna19/mypython-image
    argocd-image-updater.argoproj.io.update-strategy: digest    
spec:
  project: default
  source:
    repoURL: 'https://github.com/siva0199/kube-python.git'
    path: manifests
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
